language: go
sudo: true
go:
  - 1.7
python:
  - 2.7
install:
  - pip install --upgrade pip
  - pip install -U cookiecutter
script:
  - mkdir -p $GOPATH/src/github.com/mdevilliers
  - cookiecutter --no-input -o $GOPATH/src/github.com/mdevilliers .
  - cd $GOPATH/src/github.com/mdevilliers/awesome-service; git init; git add .; git commit -m "Initial commit"
  - cd $GOPATH/src/github.com/mdevilliers/awesome-service; make build; make image
