apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.project_name }}-deployment
  labels:
    app: {{ cookiecutter.project_name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ cookiecutter.project_name }}
  template:
    metadata:
      labels:
        app: {{ cookiecutter.project_name }}
    spec:
      containers:
        - image: {{ cookiecutter.docker_repository }}/{{ cookiecutter.project_name }}:latest
          name: {{cookiecutter.project_name}}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 3000
              protocol: TCP
