apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.project_name }}-deployment
  labels:
    app: {{ cookiecutter.project_name }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ cookiecutter.project_name }}
  template:
    metadata:
      labels:
        app: {{ cookiecutter.project_name }}
    spec:
      containers:
        - image: {{ cookiecutter.docker_repository }}/{{ cookiecutter.project_name }}:latest
          name: {{cookiecutter.project_name}}
          imagePullPolicy: "IfNotPresent"
          # define a liveness probe that checks every 5 seconds, starting after 5 seconds
          livenessProbe:
            httpGet:
              path: /live
              port: 8086
            initialDelaySeconds: 5
            periodSeconds: 5
          # define a readiness probe that checks every 5 seconds
          readinessProbe:
            httpGet:
              path: /ready
              port: 8086
            periodSeconds: 5
          ports:
            - containerPort: 3000
              protocol: TCP
